include: 
  - "https://raw.githubusercontent.com/kinhnv/Platform.Common/v1.0.6/pipeline/.prepare-ssh.yml"
  - "https://raw.githubusercontent.com/kinhnv/Platform.Common/v1.0.6/pipeline/.dotnet.yml"

stages:
  - build
  - test
  - deploy
  - pack

.production_config:
  variables:
    ASPNETCORE_ENVIRONMENT: "Production"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  
build:
  stage: build
  variables:
    VERSION: ${CI_PIPELINE_ID}
    DOCKERFILE: ${CI_PROJECT_DIR}/UserService.Api/Dockerfile
    IMAGE: registry.gitlab.com/i3rothers/user/user-service:${CI_PIPELINE_ID}
  extends:
    - .production_config
    - .dotnet_build

test:
  stage: test
  variables:
    VERSION: ${CI_PIPELINE_ID}
    UNIT_TEST_FOLDER: UserService.UnitTests
  extends:
    - .production_config
    - .dotnet_test

deploy:
  stage: deploy
  variables:
    VERSION: ${CI_PIPELINE_ID}
    TAG_CONFIG: .services.userService.tag
    VALUE_YAML_FILE: user/values.yaml
  extends:
    - .production_config
    - .dotnet_deploy
    
pack client:
  stage: pack
  variables:
    API_DIR: ${CI_PROJECT_DIR}/UserService.Api
    DOTNET_CLIENT_DIR: ${CI_PROJECT_DIR}/i3rothers.UserServiceClient
    ANGULAR_CLIENT_DIR: ${CI_PROJECT_DIR}/i3rothers.UserServiceClient/angular
    FETCH_CLIENT_DIR: ${CI_PROJECT_DIR}/i3rothers.UserServiceClient/fetch
    TEMP_DIR: ${CI_PROJECT_DIR}/UserService.Api/temp
    API_CSPROJ_FILE: ${API_DIR}/UserService.Api.csproj
    CLIENT_CS_FILE_TEMP: ${TEMP_DIR}/UserServiceClient.cs
    CLIENT_ANGULAR_FILE_TEMP: ${TEMP_DIR}/user-service-client-angular.ts
    CLIENT_FETCH_FILE_TEMP: ${TEMP_DIR}/user-service-client-fetch.ts
    CLIENT_CS_FILE: ${DOTNET_CLIENT_DIR}/UserServiceClient.cs
    CLIENT_ANGULAR_DIR: ${ANGULAR_CLIENT_DIR}/projects/user-service-client/src/lib
    CLIENT_ANGULAR_FILE: ${CLIENT_ANGULAR_DIR}/user-service-client-angular.ts
    CLIENT_FETCH_FILE: ${FETCH_CLIENT_DIR}/index.ts
    CLIENT_CSPROJ_FILE: ${DOTNET_CLIENT_DIR}/i3rothers.UserServiceClient.csproj
    CLIENT_NUPKG_FILE_NO_VERSION_AND_TYPE: ${DOTNET_CLIENT_DIR}/bin/Release/i3rothers.UserServiceClient
    PREFIX: User
    OUTPUT_DIR: ${ANGULAR_CLIENT_DIR}/dist/user-service-client
    ANGULAR_PACKAGE_FILE: ${ANGULAR_CLIENT_DIR}/projects/user-service-client/package.json
    FECTH_PACKAGE_FILE: ${FETCH_CLIENT_DIR}/package.json
  extends:
    - .production_config
    - .client_pack

