include: 
  - "https://raw.githubusercontent.com/kinhnv/Platform.Common/main/pipeline/.prepare-ssh.yml"
  - "https://raw.githubusercontent.com/kinhnv/Platform.Common/main/pipeline/.dotnet.yml"

stages:
  - build
  - test
  - deploy

.production_config:
  variables:
    ASPNETCORE_ENVIRONMENT: "Production"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  
build:
  stage: build
  variables:
    VERSION: ${CI_PIPELINE_ID}
    DOCKERFILE: ${CI_PROJECT_DIR}/UserService.Api/Dockerfile
    IMAGE: registry.gitlab.com/i3rothers/user/user-service:${CI_PIPELINE_ID}
  extends:
    - .production_config
    - .dotnet_build

test:
  stage: test
  variables:
    VERSION: ${CI_PIPELINE_ID}
    UNIT_TEST_FOLDER: UserService.UnitTests
  extends:
    - .production_config
    - .dotnet_test

deploy:
  stage: deploy
  variables:
    VERSION: ${CI_PIPELINE_ID}
    TAG_CONFIG: .services.userService.tag
    VALUE_YAML_FILE: user/values.yaml
  extends:
    - .production_config
    - .dotnet_deploy