variables:
  VERSION: "$CI_PIPELINE_ID"
  ASPNETCORE_ENVIRONMENT: "Production"

stages:
  - build
  - update_github
  - test
  - update_gitops

before_script:
  - eval "$(ssh-agent -s)"
  - cat ~/.ssh/id_rsa | ssh-add - > /dev/null
  - ssh-keyscan github.com >> ~/.ssh/known_hosts

build-user-service:
  stage: build
  only:
    - master
  script:
    - docker-compose -f docker-compose-user-service.yml build
    - docker-compose -f docker-compose-user-service.yml push

build-identity-server:
  stage: build
  only:
    - master
  script:
    - docker-compose -f docker-compose-identity-server.yml build
    - docker-compose -f docker-compose-identity-server.yml push

update-github:
  stage: update_github
  only:
    - master
  script:
    - ssh git@github.com || true
    - git remote remove origin && git remote add origin $GITHUB_URL
    - git config --global --add safe.directory $(pwd)
    - git fetch --unshallow $GITHUB_URL || true
    - git push origin HEAD:master -f
    - git config --global --unset safe.directory $(pwd) || true

test:
  stage: test
  only:
    - master
  needs:
    - build-user-service
    - build-identity-server
  script:
    - echo "done"
        
update-gitops:
  stage: update_gitops
  only:
    - master
  needs: [test]
  script:
    - echo "update-gitops"
    - git clone $GITOPS_URL 
    - cd GitOps
    - git config --global --add safe.directory $(pwd)
    - git checkout -b test-maker origin/test-maker
    - sed -i "s/test-maker.user-service:[0-9]*/test-maker.user-service:$VERSION/g" ./setup/user-service.deployment.yml
    - git add ./setup/user-service.deployment.yml
    - sed -i "s/test-maker.identity-server:[0-9]*/test-maker.identity-server:$VERSION/g" ./setup/identity-server.deployment.yml
    - git add ./setup/identity-server.deployment.yml
    - git config --global user.email "kinhnv1801@gmail.com"
    - git config --global user.name "Nguyen Van Kinh"
    - git commit -m "change to version $VERSION"
    - git push origin test-maker
    - git config --global --unset safe.directory $(pwd) || true
